############################################################################
# U S E R - D E F A U L T
############################################################################
spring:
  profiles:
    active: development
  jmx:
    enabled: false
  data:
    mongodb:
      database: store
      port: 27017


#swagger
swagger:
  config:
    apiInfo:
      title: Checkout API
      description: Checkout API.
      version: 1.0.0 
      termsOfServiceUrl: Jorge Filho
      contact: papachristo@gmail.com
      license: https://github.com/jorgefilho/store
      licenseUrl: https://github.com/jorgefilho/store

#spring-boot endpoints
endpoints:
  enabled: true
  info:
    enabled: true
  health:
    sensitive: false

#security
security:
  basic:
    enabled: false
#server
server:
  port: 8080

management:
  port: 8080
  address: 127.0.0.1
  security:
    enabled: false
  


