spring:
  profiles:
    active: development
  jmx:
    enabled: false
  data:
    mongodb:
      database: store
      port: 27017
  session:
    store-type: redis
#server
server:
  port: 8080
  session:
    timeout: 50000

management:
  port: 8080
  address: 127.0.0.1
  security:
    enabled: false

#spring-boot endpoints
endpoints:
  enabled: false
  info:
    enabled: false
  health:
    sensitive: false
#security
security:
  basic:
    enabled: false

#swagger
swagger:
  config:
    apiInfo:
      title: Checkout API
      description: Checkout API.
      version: 1.0.0 
      termsOfServiceUrl: Jorge Filho
      contact: papachristo@gmail.com
      license: https://github.com/jorgefilho/store
      licenseUrl: https://github.com/jorgefilho/store

